name: Waka Readme & Profile Summary Cards

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_COMMIT: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_LOC_CHART: "false" # 代码行数图表可能过大，可选择关闭
          SHOW_PROFILE_VIEWS: "true"
          SHOW_LANGUAGES: "true"
          SHOW_LINES_OF_CODE: "true"
